export const NETWORK_PROTOCOL_VERSION=1 as const;
export const MAX_NETWORK_PAYLOAD_BYTES=64*1024;
export const MIN_NETWORK_TTL_SECONDS=10;
export const MAX_NETWORK_TTL_SECONDS=3600;
export type AgentNetworkMessageKind="request"|"response"|"event"|"delegation";
export type AgentNetworkEnvelope={protocolVersion:typeof NETWORK_PROTOCOL_VERSION;organizationId:string;messageId:string;senderAgentId:string;recipientAgentId:string;conversationId:string;correlationId:string|null;replyToMessageId:string|null;kind:AgentNetworkMessageKind;scope:string;subject:string;payloadHash:string;createdAt:string;expiresAt:string;nonce:string};
export function canonicalJson(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return"["+v.map(canonicalJson).join(",")+"]";const r=v as Record<string,unknown>;return"{"+Object.keys(r).sort().map(k=>JSON.stringify(k)+":"+canonicalJson(r[k])).join(",")+"}";}
export function buildNetworkSigningPayload(envelope:AgentNetworkEnvelope):string{return canonicalJson(envelope);}
export function validateNetworkEnvelope(envelope:AgentNetworkEnvelope,nowMs=Date.now()){if(envelope.protocolVersion!==NETWORK_PROTOCOL_VERSION)throw new Error("Unsupported network protocol version");if(!/^[0-9a-f]{64}$/.test(envelope.payloadHash))throw new Error("Invalid payload hash");if(!envelope.organizationId||!envelope.senderAgentId||!envelope.recipientAgentId||envelope.senderAgentId===envelope.recipientAgentId)throw new Error("Invalid network participants");if(!envelope.messageId||!envelope.nonce||!envelope.subject)throw new Error("Incomplete network envelope");if(!envelope.scope||envelope.scope.length>120)throw new Error("Invalid network scope");const created=Date.parse(envelope.createdAt),expires=Date.parse(envelope.expiresAt);if(!Number.isFinite(created)||!Number.isFinite(expires)||expires<=created)throw new Error("Invalid network timestamps");const ttl=(expires-created)/1000;if(ttl<MIN_NETWORK_TTL_SECONDS||ttl>MAX_NETWORK_TTL_SECONDS)throw new Error("Network TTL is outside the allowed range");if(nowMs>expires)throw new Error("Network envelope is expired");if(envelope.kind==="response"&&!envelope.replyToMessageId)throw new Error("Responses must reference a prior message");if(envelope.kind==="delegation"&&!(/^agent\.delegation(?:\.|$)/.test(envelope.scope)))throw new Error("Delegation requires an agent.delegation scope");return true;}
export function messagePayloadSizeBytes(payload:unknown){return new TextEncoder().encode(JSON.stringify(payload)).byteLength;}
