"use client";
import{useEffect,useState}from"react";
export default function EnterprisePage(){const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[teamName,setTeamName]=useState("");const[teamDescription,setTeamDescription]=useState("");const[inviteEmail,setInviteEmail]=useState("");const[inviteRole,setInviteRole]=useState("member");const[inviteToken,setInviteToken]=useState("");
async function load(){setLoading(true);const r=await fetch("/api/enterprise");const b=await r.json();if(!r.ok){setMessage(b.error??"Enterprise control plane unavailable");setLoading(false);return;}setData(b);setLoading(false);}
useEffect(()=>{void load();},[]);
async function save(section:string,value:any){setMessage("Saving…");const r=await fetch("/api/enterprise",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({section,value})});const b=await r.json();if(!r.ok){setMessage(b.error??"Save failed");return;}await load();setMessage("Saved");}
async function createTeam(){const r=await fetch("/api/enterprise/teams",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:teamName,description:teamDescription})});const b=await r.json();if(!r.ok){setMessage(b.error??"Team creation failed");return;}setTeamName("");setTeamDescription("");await load();}
async function invite(){const r=await fetch("/api/enterprise/invitations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:inviteEmail,role:inviteRole})});const b=await r.json();if(!r.ok){setMessage(b.error??"Invitation failed");return;}setInviteToken(b.token??"");setInviteEmail("");await load();}
if(loading)return <main className="shell"><section className="card"><b>Loading enterprise control plane…</b></section></main>;
const e=data?.entitlements,p=data?.policy,u=data?.usage;return <main className="shell"><header className="topbar"><div><div className="eyebrow">ENTERPRISE CONTROL PLANE · V5</div><h1>{data?.organization?.name??"Organization"}</h1></div><div className="topMeta"><span>{e?.plan??"starter"} plan</span><a href="/">Orchestrator</a><a href="/auth/sign-in">Account</a></div></header>{message&&<div className="card" style={{marginBottom:16}}>{message}</div>}
<section className="hero card"><div><div className="pill">GOVERNANCE + USAGE + POLICY</div><h2>One control plane for people, budget, policy and execution geography.</h2><p className="muted">V5 wraps the V4 orchestrator with tenant RBAC, hard admission ceilings, metering, audit, regional policy and declarative SLA targets.</p></div><div className="healthGrid"><Metric label="Monthly spend" value={"$"+((u?.spendCents??0)/100).toFixed(2)+" / $"+((e?.monthlySpendLimitCents??0)/100).toFixed(2)}/><Metric label="Tasks" value={(u?.taskCount??0)+" / "+(e?.monthlyTaskLimit??0)}/><Metric label="Concurrency" value={String(e?.maxConcurrency??0)}/><Metric label="Region" value={e?.primaryRegion??"—"}/></div></section>
<section className="layout"><div className="card"><div className="sectionTitle">Entitlements</div><div className="metricGrid"><Metric label="Max agents" value={String(e?.maxAgents)}/><Metric label="Max members" value={String(e?.maxMembers)}/><Metric label="Max task" value={"$"+((e?.maxTaskCostCents??0)/100).toFixed(2)}/><Metric label="Retention" value={(e?.retentionDays??0)+"d"}/></div><div className="muted tiny">Starter defaults are persisted per organization. Upgrade/contract changes remain an explicit admin action.</div></div>
<div className="card"><div className="sectionTitle">External action policy</div><label><input type="checkbox" checked={Boolean(p?.requireApprovalForExternal)} onChange={ev=>save("policy",{...p,requireApprovalForExternal:ev.target.checked})}/> Require approval for external actions</label><label><input type="checkbox" checked={Boolean(p?.allowExternalActions)} onChange={ev=>save("policy",{...p,allowExternalActions:ev.target.checked})}/> Allow external action preparation</label><div className="muted small">V4 connector requests remain approval-gated; V5 does not enable arbitrary network side effects.</div></div></section>
<section className="layout"><div className="card"><div className="sectionTitle">Teams</div>{(data?.teams??[]).map((t:any)=><div className="agentRow" key={t.id}><div><b>{t.name}</b><div className="muted small">{t.description||"No description"}</div></div></div>)}<div className="composerRow"><input placeholder="Team name" value={teamName} onChange={x=>setTeamName(x.target.value)}/><input placeholder="Description" value={teamDescription} onChange={x=>setTeamDescription(x.target.value)}/><button disabled={!teamName.trim()} onClick={createTeam}>Create team</button></div></div>
<div className="card"><div className="sectionTitle">Members & invitations</div>{(data?.members??[]).map((m:any)=><div className="agentRow" key={m.user_id}><div><b>{String(m.user_id).slice(0,8)}…</b><div className="muted small">{m.role}</div></div></div>)}<div className="composerRow"><input type="email" placeholder="Invite email" value={inviteEmail} onChange={x=>setInviteEmail(x.target.value)}/><select value={inviteRole} onChange={x=>setInviteRole(x.target.value)}><option>member</option><option>operator</option><option>billing</option><option>auditor</option><option>viewer</option></select><button disabled={!inviteEmail.includes("@")} onClick={invite}>Create invite</button></div>{inviteToken&&<div className="resultBox"><div className="muted small">ONE-TIME INVITATION TOKEN</div><code>{inviteToken}</code><div className="muted tiny">Stored server-side only as a hash; copy it to your approved invitation channel.</div></div>}</div></section>
<section className="card"><div className="sectionTitle">SLA definition</div>{(data?.sla??[]).map((s:any)=><div className="agentRow" key={s.id}><div><b>{s.name}</b><div className="muted small">{(s.availabilityBps/100).toFixed(2)}% availability target · {Math.round(s.taskP95Ms/1000)}s task p95 · {s.supportResponseMinutes}m support response</div></div><span>{s.active?"active":"inactive"}</span></div>)}</section>
<section className="card"><div className="sectionTitle">Audit preview</div>{(data?.auditPreview??[]).map((a:any)=><div className="agentRow" key={a.id}><div><b>{a.action}</b><div className="muted tiny">{a.resourceType} · {a.createdAt}</div></div><span>{a.result}</span></div>)}{!data?.auditPreview?.length&&<div className="empty">Enterprise configuration changes will appear here.</div>}</section>
<section className="card"><div className="sectionTitle">Regional policy</div><div className="muted small">Primary: <b>{e?.primaryRegion}</b> · Allowed: {(e?.allowedRegions??[]).join(", ")} · Residency: {e?.dataResidency}</div><div className="muted tiny">The database task-admission trigger enforces the region allowlist before insertion.</div></section></main>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><div className="muted small">{label}</div><b>{value}</b></div>}