"use client";
import{useEffect,useState,type CSSProperties}from"react";
export default function NetworkPage(){const[agents,setAgents]=useState<any[]>([]),[peers,setPeers]=useState<any[]>([]),[messages,setMessages]=useState<any[]>([]),[stats,setStats]=useState<any>(null),[org,setOrg]=useState<any>(null),[peerSource,setPeerSource]=useState(""),[peerTarget,setPeerTarget]=useState(""),[messageSource,setMessageSource]=useState(""),[messageTarget,setMessageTarget]=useState(""),[scope,setScope]=useState("task.coordination"),[subject,setSubject]=useState("Coordination request"),[body,setBody]=useState("{\n  \"instruction\": \"Pass verified context to the next agent\"\n}"),[status,setStatus]=useState("");
async function load(){const a=await fetch("/api/agents");if(!a.ok){setStatus("Sign in to access the agent network.");return;}const ad=await a.json();setAgents(ad.agents??[]);setOrg(ad.organization);const ps=await fetch("/api/network/peers");if(ps.ok)setPeers((await ps.json()).peers??[]);const ms=await fetch("/api/network?limit=50");if(ms.ok){const md=await ms.json();setMessages(md.messages??[]);setStats(md.stats);}}useEffect(()=>{void load();const h=window.setInterval(()=>void load(),4000);return()=>window.clearInterval(h);},[]);
async function createPeer(){setStatus("Authorizing trust edge…");const r=await fetch("/api/network/peers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceAgentId:peerSource,targetAgentId:peerTarget,allowedMessageTypes:["request","response","event"],allowedScopes:[scope],maxPayloadBytes:65536,rateLimitPerMinute:60})});const b=await r.json();setStatus(r.ok?"Trust edge active.":(b.error??"Peer creation failed"));if(r.ok)await load();}
async function revokePeer(id:string){const r=await fetch("/api/network/peers/"+id+"?organizationId="+encodeURIComponent(org.id),{method:"DELETE"});const b=await r.json();setStatus(r.ok?"Trust edge revoked.":(b.error??"Revocation failed"));await load();}
async function send(){let payload:any;try{payload=JSON.parse(body);}catch{setStatus("Payload must be valid JSON.");return;}setStatus("Signing and enqueueing…");const r=await fetch("/api/network",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId:org?.id,senderAgentId:messageSource,recipientAgentId:messageTarget,subject,payload,scope,kind:"event",ttlSeconds:300,priority:60})});const b=await r.json();setStatus(r.ok?"Message queued with signed provenance.":(b.error??"Message rejected"));if(r.ok)await load();}
async function claim(){if(!messageTarget){setStatus("Select the recipient agent to claim its inbox.");return;}const r=await fetch("/api/network/claim?organizationId="+encodeURIComponent(org.id),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:messageTarget,limit:20})});const b=await r.json();setStatus(r.ok?"Inbox claimed: "+(b.messages?.length??0)+" message(s).":(b.error??"Claim failed"));await load();}
async function ack(m:any,success:boolean){const r=await fetch("/api/network/messages/"+m.messageId+"/ack?organizationId="+encodeURIComponent(org.id),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({agentId:m.recipientAgentId,success})});const b=await r.json();setStatus(r.ok?(success?"Message acknowledged.":"Message failed."):(b.error??"Acknowledgement failed"));await load();}
return <main className="shell"><header className="topbar"><div><div className="eyebrow">AGENT NETWORK · V6</div><h1>Agent-to-agent network</h1></div><div className="topMeta"><span>{org?.name??"No workspace"}</span><span>{stats?.activePeers??0} trust edges</span><span>{stats?.queued??0} queued</span><a href="/">Orchestrator</a><a href="/enterprise">Enterprise</a></div></header>
<section className="hero card"><div><div className="pill">SIGNED · ENCRYPTED · DURABLE</div><h2>Agents can coordinate without bypassing the V5 control plane.</h2><p className="muted">Every message crosses an explicit trust edge, carries an Ed25519 signature, is encrypted at rest, expires, rate-limits, and produces immutable delivery history.</p></div><div className="healthGrid"><Metric label="Active peers" value={String(stats?.activePeers??0)}/><Metric label="Queued" value={String(stats?.queued??0)}/><Metric label="Delivered" value={String(stats?.delivered??0)}/><Metric label="Acknowledged" value={String(stats?.acknowledged??0)}/></div></section>
<section className="layout"><div className="card" style={{padding:20}}><div className="sectionTitle">Trust graph</div><div className="composerRow"><select value={peerSource} onChange={e=>setPeerSource(e.target.value)} style={fieldStyle}><option value="">Source agent</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={peerTarget} onChange={e=>setPeerTarget(e.target.value)} style={fieldStyle}><option value="">Target agent</option>{agents.filter(a=>a.id!==peerSource).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div><input value={scope} onChange={e=>setScope(e.target.value)} placeholder="Allowed scope" style={fieldStyle}/><button onClick={createPeer} disabled={!peerSource||!peerTarget||!scope}>Create trust edge</button>{peers.map(p=><div className="agentRow" key={p.id}><div className="agentDot"/><div><b>{p.sourceAgentId} → {p.targetAgentId}</b><div className="muted small">{p.allowedMessageTypes.join(" · ")} · {p.allowedScopes.join(" · ")} · {p.rateLimitPerMinute}/min</div></div><div className="agentRight"><span>{p.status}</span>{p.status==="active"&&<button className="secondary" onClick={()=>revokePeer(p.id)}>Revoke</button>}</div></div>)}</div>
<div className="card" style={{padding:20}}><div className="sectionTitle">Send + deliver</div><select value={messageSource} onChange={e=>setMessageSource(e.target.value)} style={fieldStyle}><option value="">Sender agent</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={messageTarget} onChange={e=>setMessageTarget(e.target.value)} style={fieldStyle}><option value="">Recipient agent</option>{agents.filter(a=>a.id!==messageSource).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Subject" style={fieldStyle}/><textarea value={body} onChange={e=>setBody(e.target.value)} style={{...fieldStyle,minHeight:150,fontFamily:"ui-monospace,monospace"}}/><div className="composerRow"><button onClick={send} disabled={!org||!messageSource||!messageTarget||!subject}>Sign + enqueue</button><button className="secondary" onClick={claim} disabled={!org||!messageTarget}>Claim recipient inbox</button></div><div className="muted small" style={{marginTop:10}}>Delegation is intentionally not exposed in this UI; granting it requires an explicit agent.delegation trust scope.</div></div></section>
<section className="card" style={{padding:20,marginTop:16}}><div className="sectionTitle">Delivery inbox</div>{messages.length===0?<div className="empty">No network messages yet.</div>:messages.map(m=><div className="agentRow" key={m.id}><div className="agentDot"/><div><b>{m.subject}</b><div className="muted small">{m.senderAgentId} → {m.recipientAgentId} · {m.kind} · {m.scope}</div><div className="muted small">status {m.status} · attempts {m.attemptCount} · expires {new Date(m.expiresAt).toLocaleString()}</div>{m.payload!==undefined&&<pre style={{margin:"8px 0 0",whiteSpace:"pre-wrap",color:"var(--muted)",fontSize:11}}>{JSON.stringify(m.payload,null,2)}</pre>}</div><div className="agentRight">{m.status==="delivered"&&<><button onClick={()=>ack(m,true)}>Ack</button><button className="secondary" onClick={()=>ack(m,false)}>Fail</button></>}</div></div>)}</section>{status&&<div className="error">{status}</div>}</main>}
const fieldStyle:CSSProperties={width:"100%",marginTop:10,background:"#08120c",color:"var(--text)",border:"1px solid var(--line)",borderRadius:11,padding:12,font:"inherit"};
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><div className="muted small">{label}</div><b>{value}</b></div>}
