import{createCipheriv,createDecipheriv,createHash,randomBytes}from"node:crypto";
export interface EncryptedSecret{ciphertext:string;iv:string;authTag:string;keyVersion:number;}
function readKey(v:number):Buffer{const raw=process.env[`CREDENTIAL_MASTER_KEY_V${v}`];if(!raw)throw new Error(`CREDENTIAL_MASTER_KEY_V${v} is not configured`);const key=/^[0-9a-fA-F]{64}$/.test(raw)?Buffer.from(raw,"hex"):Buffer.from(raw,"base64");if(key.length!==32)throw new Error("Credential master key must decode to exactly 32 bytes");return key;}
export function activeKeyVersion(){const v=Number(process.env.CREDENTIAL_ACTIVE_KEY_VERSION??"1");if(!Number.isInteger(v)||v<1||v>50)throw new Error("Invalid CREDENTIAL_ACTIVE_KEY_VERSION");return v;}
export function encryptSecret(plaintext:string,keyVersion=activeKeyVersion()):EncryptedSecret{if(typeof plaintext!=="string"||plaintext.length<1||plaintext.length>100000)throw new Error("Credential secret must be a non-empty string of at most 100,000 characters");const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",readKey(keyVersion),iv);const ciphertext=Buffer.concat([cipher.update(plaintext,"utf8"),cipher.final()]);return{ciphertext:ciphertext.toString("base64"),iv:iv.toString("base64"),authTag:cipher.getAuthTag().toString("base64"),keyVersion};}
export function decryptSecret(i:EncryptedSecret){const d=createDecipheriv("aes-256-gcm",readKey(i.keyVersion),Buffer.from(i.iv,"base64"));d.setAuthTag(Buffer.from(i.authTag,"base64"));return Buffer.concat([d.update(Buffer.from(i.ciphertext,"base64")),d.final()]).toString("utf8");}
export function canonicalJson(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalJson).join(",")}]`;const r=v as Record<string,unknown>;return`{${Object.keys(r).sort().map(k=>`${JSON.stringify(k)}:${canonicalJson(r[k])}`).join(",")}}`;}
export function sha256(v:string){return createHash("sha256").update(v,"utf8").digest("hex");}
export function hashJson(v:unknown){return sha256(canonicalJson(v));}
