// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import { default as handler } from "../.open-next/worker.js";
import { dispatchDueTasks, executeQueuedTask } from "../lib/orchestrator/background";

type QueueMessage = {
  body: {
    schemaVersion?: number;
    dispatchId?: string;
    taskId?: string;
    organizationId?: string;
    reason?: string;
    enqueuedAt?: string;
  };
  id: string;
  attempts?: number;
  ack?: () => void;
  retry?: (options?: { delaySeconds?: number }) => void;
};

type RuntimeEnv = Record<string, unknown> & {
  TASK_QUEUE?: unknown;
};

function retryDelay(attempts: number) {
  return Math.min(300, 15 * Math.max(1, attempts));
}

const worker = {
  fetch: handler.fetch,

  async queue(batch: { messages: QueueMessage[] }, env: RuntimeEnv) {
    for (const message of batch.messages) {
      const body = message.body ?? {};
      if (body.schemaVersion !== 1 || !body.taskId || !body.organizationId || !body.dispatchId) {
        message.retry?.({ delaySeconds: 30 });
        continue;
      }

      try {
        await executeQueuedTask({
          taskId: body.taskId,
          organizationId: body.organizationId,
          dispatchId: body.dispatchId,
          queueMessageId: message.id,
          attempt: Math.max(1, Math.floor(message.attempts ?? 1)),
          runtimeEnv: env,
        });
        message.ack?.();
      } catch {
        message.retry?.({ delaySeconds: retryDelay(message.attempts ?? 1) });
      }
    }
  },

  async scheduled(_event: { cron?: string }, env: RuntimeEnv) {
    try {
      await dispatchDueTasks(env, "cron");
    } catch (error) {
      console.error(JSON.stringify({
        event: "ops.cron_dispatch_failed",
        error: error instanceof Error ? error.message.slice(0, 240) : "unknown",
      }));
    }
  },
};

export default worker;
