// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import { default as handler } from "../.open-next/worker.js";
import { dispatchDueTasks, executeQueuedTask } from "../lib/orchestrator/background";
import { recordBackgroundDeadLetter, sweepRuntimeIntegrity } from "../lib/ops/repository";

type QueueMessage = {
  body: {
    schemaVersion?: number;
    dispatchId?: string;
    taskId?: string;
    organizationId?: string;
    reason?: string;
    enqueuedAt?: string;
  };
  id: string;
  attempts?: number;
  ack?: () => void;
  retry?: (options?: { delaySeconds?: number }) => void;
};

type RuntimeEnv = Record<string, unknown> & {
  TASK_QUEUE?: unknown;
};

function retryDelay(attempts: number) {
  return Math.min(300, 15 * Math.max(1, attempts));
}

const worker = {
  fetch: handler.fetch,

  async queue(batch: { messages: QueueMessage[] }, env: RuntimeEnv) {
    const maxRetries = Math.max(1, Math.floor(Number((env as Record<string, unknown>).TASK_QUEUE_MAX_RETRIES ?? 5)));
    for (const message of batch.messages) {
      const body = message.body ?? {};
      const attempt = Math.max(1, Math.floor(message.attempts ?? 1));
      if (body.schemaVersion !== 1 || !body.taskId || !body.organizationId || !body.dispatchId) {
        if (attempt >= maxRetries) {
          await recordBackgroundDeadLetter({
            organizationId: typeof body.organizationId === "string" ? body.organizationId : null,
            taskId: typeof body.taskId === "string" ? body.taskId : null,
            dispatchId: typeof body.dispatchId === "string" ? body.dispatchId : null,
            queueMessageId: message.id,
            attempts: attempt,
            reason: "Invalid queue task envelope",
            metadata: { schemaVersion: body.schemaVersion ?? null },
          }).catch(() => {});
        }
        message.retry?.({ delaySeconds: 30 });
        continue;
      }

      try {
        await executeQueuedTask({
          taskId: body.taskId,
          organizationId: body.organizationId,
          dispatchId: body.dispatchId,
          queueMessageId: message.id,
          attempt,
          runtimeEnv: env,
        });
        message.ack?.();
      } catch (error) {
        if (attempt >= maxRetries) {
          await recordBackgroundDeadLetter({
            organizationId: body.organizationId,
            taskId: body.taskId,
            dispatchId: body.dispatchId,
            queueMessageId: message.id,
            attempts: attempt,
            reason: error instanceof Error ? error.message : "Queue task execution failed",
            metadata: { trigger: "queue" },
          }).catch(() => {});
        }
        message.retry?.({ delaySeconds: retryDelay(attempt) });
      }
    }
  },

  async scheduled(_event: { cron?: string }, env: RuntimeEnv) {
    try {
      await sweepRuntimeIntegrity({
        staleLeaseSeconds: Number(env.TASK_STALE_LEASE_TAKEOVER_SECONDS ?? 300),
        staleWorkerRunSeconds: Number(env.TASK_STALE_WORKER_RUN_SECONDS ?? 900),
        maxTasks: Number(env.BACKGROUND_DISPATCH_LIMIT ?? 12),
      });
      await dispatchDueTasks(env, "cron");
    } catch (error) {
      console.error(JSON.stringify({
        event: "ops.cron_dispatch_failed",
        error: error instanceof Error ? error.message.slice(0, 240) : "unknown",
      }));
    }
  },
};

export default worker;
